# Island-compilable-rate survey over the featured-notebook corpus.
#
# For every notebook in test/notebooks/featured/: run it (real Pluto run —
# first time may install that notebook's packages), extract bond groups
# (M1), and report how many groups/cells are extraction-ok and why the rest
# fail. Writes tools/ISLAND_SURVEY.md.
#
# This number is the headline metric for the wasm-islands effort, and each
# failure reason is a WasmTarget/extractor work item (the feedback loop).
#
# Run:  julia --project=. tools/island_survey.jl [pattern]

import Pluto
using FromFile

@from "../src/islands/extract.jl" import extract_groups, is_ok, ExtractedGroup

const CORPUS = joinpath(@__DIR__, "..", "test", "notebooks", "featured")
const REPORT = joinpath(@__DIR__, "ISLAND_SURVEY.md")

# lightest-deps first, so partial runs already produce useful rows
const ORDER = [
    "Interactivity with HTML.jl",
    "Basic mathematics.jl",
    "CollatzConjecture.jl",
    "newton.jl",
    "PlutoUI.jl.jl",
    "fractals.jl",
    "convolution_1d.jl",
    "convolution_2d.jl",
    "images.jl",
    "dither.jl",
    "turtles-art.jl",
    "Titration.jl",
]

pattern = isempty(ARGS) ? "" : ARGS[1]
files = [f for f in ORDER if isfile(joinpath(CORPUS, f)) && occursin(pattern, f)]

session = Pluto.ServerSession()

rows = []
for (i, f) in enumerate(files)
    path = joinpath(CORPUS, f)
    @info "[$i/$(length(files))] running + extracting" f
    t0 = time()
    row = try
        notebook = Pluto.SessionActions.open(session, path; run_async=false)
        original_state = Pluto.notebook_to_js(notebook)
        groups = extract_groups(session, notebook; original_state)
        n_cells = sum(g -> length(g.cell_plans), groups; init=0)
        ok_cells = sum(g -> count(p -> p.ok, g.cell_plans), groups; init=0)
        reasons = String[]
        for g in groups
            append!(reasons, g.reasons)
            for p in g.cell_plans
                p.ok || append!(reasons, p.reasons)
            end
        end
        Pluto.SessionActions.shutdown(session, notebook; async=false)
        (; f, ok=true, n_groups=length(groups), ok_groups=count(is_ok, groups),
           n_cells, ok_cells, reasons, t=round(time() - t0; digits=1))
    catch e
        (; f, ok=false, n_groups=0, ok_groups=0, n_cells=0, ok_cells=0,
           reasons=["notebook run failed: $(sprint(showerror, e)[1:min(end, 200)])"],
           t=round(time() - t0; digits=1))
    end
    push!(rows, row)

    # (Re)write the report after every notebook — survey is resumable/partial
    open(REPORT, "w") do io
        println(io, "# Island-compilable rate — featured corpus (M1 extraction stage)\n")
        println(io, "Generated by `tools/island_survey.jl`. Extraction-stage judgement only —")
        println(io, "wasm compilation (M2) and the differential oracle (M4) judge further.\n")
        println(io, "| notebook | groups ok | cells ok | run+extract s |")
        println(io, "|---|---|---|---|")
        for r in rows
            println(io, "| $(r.f) | $(r.ok_groups)/$(r.n_groups) | $(r.ok_cells)/$(r.n_cells) | $(r.t) |")
        end
        println(io, "\n## Failure reasons (deduped per notebook)\n")
        for r in rows
            isempty(r.reasons) && continue
            println(io, "**$(r.f)**")
            for reason in unique(r.reasons)
                n = count(==(reason), r.reasons)
                println(io, "- $(reason)$(n > 1 ? " ×$n" : "")")
            end
            println(io)
        end
    end
    @info "  → groups $(row.ok_groups)/$(row.n_groups), cells $(row.ok_cells)/$(row.n_cells) ($(row.t)s)"
end

println("SURVEY DONE → ", REPORT)
