# Full-pipeline island survey over the featured-notebook corpus (E-006).
#
# For every notebook in test/notebooks/featured/: real Pluto run, then the
# COMPLETE export pipeline — extraction, per-cell wasm compile, Node verify,
# differential oracle — via generate_wasm_islands. The headline metric is
# shipped groups (judgement "island" or "partial") over total bond groups.
# Canvas (WasmMakie figure) cells ship through the E-004 path; notebooks on
# other plotting stacks degrade honestly and their reasons are the work list.
#
# Writes tools/ISLAND_SURVEY.md after every notebook (resumable/partial).
#
# Run:  julia +1.12 --project=. tools/island_survey_full.jl [pattern]

import Pluto
import JSON
using Snapshot

const CORPUS = joinpath(@__DIR__, "..", "test", "notebooks", "featured")
const REPORT = joinpath(@__DIR__, "ISLAND_SURVEY.md")

# lightest-deps first, so partial runs already produce useful rows
const ORDER = [
    "Interactivity with HTML.jl",
    "Basic mathematics.jl",
    "CollatzConjecture.jl",
    "newton.jl",
    "PlutoUI.jl.jl",
    "fractals.jl",
    "convolution_1d.jl",
    "convolution_2d.jl",
    "images.jl",
    "dither.jl",
    "turtles-art.jl",
    "Titration.jl",
    "eeg_features.jl",
]

pattern = isempty(ARGS) ? "" : ARGS[1]
files = [f for f in ORDER if isfile(joinpath(CORPUS, f)) && occursin(pattern, f)]

session = Pluto.ServerSession()

rows = []
function write_report()
    n_groups = sum(r -> r.n, rows; init=0)
    n_island = sum(r -> r.island, rows; init=0)
    n_partial = sum(r -> r.partial, rows; init=0)
    open(REPORT, "w") do io
        println(io, "# Island rate — featured corpus (FULL pipeline: compile + verify + oracle)\n")
        println(io, "Generated by `tools/island_survey_full.jl`. A group **ships** when its")
        println(io, "judgement is `island` (all cells live) or `partial` (some cells live,")
        println(io, "the rest decorated). Canvas (WasmMakie figure) cells ship via E-004.\n")
        println(io, "**Headline: $(n_island + n_partial)/$(n_groups) groups ship** ($(n_island) island + $(n_partial) partial)\n")
        println(io, "| notebook | island | partial | fallback | groups | s |")
        println(io, "|---|---|---|---|---|---|")
        for r in rows
            println(io, "| $(r.f) | $(r.island) | $(r.partial) | $(r.n - r.island - r.partial) | $(r.n) | $(r.t) |")
        end
        println(io, "\n## Degradation reasons (deduped per notebook)\n")
        for r in rows
            isempty(r.reasons) && continue
            println(io, "**$(r.f)**")
            for reason in unique(r.reasons)
                n = count(==(reason), r.reasons)
                println(io, "- $(reason)$(n > 1 ? " ×$n" : "")")
            end
            println(io)
        end
    end
end

for (i, f) in enumerate(files)
    path = joinpath(CORPUS, f)
    @info "[$i/$(length(files))] full export pipeline" f
    t0 = time()
    row = try
        out = mktempdir()
        notebook = Pluto.SessionActions.open(session, path; run_async=false)
        original_state = Pluto.notebook_to_js(notebook)
        delete!(original_state, "status_tree")
        generate_wasm_islands(session, notebook, original_state;
                              output_dir=out, url_path=basename(path))
        Pluto.SessionActions.shutdown(session, notebook; async=false)
        name = Pluto.without_pluto_file_extension(basename(path))
        report_path = joinpath(out, name * ".islands", "report.json")
        rep = isfile(report_path) ? JSON.parsefile(report_path) : Any[]
        island = count(r -> r["judgement"] == "island", rep)
        partial = count(r -> r["judgement"] == "partial", rep)
        reasons = String[]
        for r in rep
            r["judgement"] == "island" && continue
            for x in something(r["reasons"], Any[])
                push!(reasons, string(x))
            end
            for c in something(r["cells"], Any[])
                get(c, "ok", true) && continue
                for x in get(c, "reasons", Any[])
                    push!(reasons, string(x))
                end
            end
        end
        (; f, ok=true, n=length(rep), island, partial, reasons,
           t=round(time() - t0; digits=1))
    catch e
        (; f, ok=false, n=0, island=0, partial=0,
           reasons=["notebook run failed: $(sprint(showerror, e)[1:min(end, 200)])"],
           t=round(time() - t0; digits=1))
    end
    push!(rows, row)
    write_report()
    @info "  → island $(row.island) + partial $(row.partial) of $(row.n) groups ($(row.t)s)"
end

n_groups = sum(r -> r.n, rows; init=0)
n_ship = sum(r -> r.island + r.partial, rows; init=0)
println("SURVEY DONE: $(n_ship)/$(n_groups) groups ship → ", REPORT)
